In [13]:
import torch
import torch.nn as nn

## First, some random practice

In [14]:
a = torch.randn(4, 4)
a

tensor([[-0.7444,  1.0120,  0.3675,  2.6592],
        [-0.9483, -1.0301, -0.1990, -0.2448],
        [-0.7577,  1.1288, -0.9627,  0.4792],
        [-1.9023, -0.7524, -0.5739, -0.4064]])

In [48]:
mask = torch.tril(torch.ones_like(a, dtype=torch.bool))
print(f"Mask with only triangular booleans:\n{mask}")
mask = mask == 0 # logic: True == 0 is False, False == 0 is True
print(f"\nMask after doing == 0:\n{mask}")
b = a.masked_fill(mask=mask, value=torch.tensor(float('-inf')))
print(f"\nMasked matrix:\n{b}")

Mask with only triangular booleans:
tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False],
        [ True,  True,  True,  True]])

Mask after doing == 0:
tensor([[False,  True,  True,  True],
        [False, False,  True,  True],
        [False, False, False,  True],
        [False, False, False, False]])

Masked matrix:
tensor([[-0.7444,    -inf,    -inf,    -inf],
        [-0.9483, -1.0301,    -inf,    -inf],
        [-0.7577,  1.1288, -0.9627,    -inf],
        [-1.9023, -0.7524, -0.5739, -0.4064]])


In [32]:
c = torch.softmax(b, dim=-1)
c

tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.5204, 0.4796, 0.0000, 0.0000],
        [0.1189, 0.7843, 0.0969, 0.0000],
        [0.0807, 0.2547, 0.3045, 0.3600]])

## Time to build the masked self-attention

In [ ]:
class MaskedSelfAttention(nn.Module):
    def __init__(self, embed_dim=5, row_index=0, col_index=1):
        self.W_q = nn.Linear(
            in_features=embed_dim, out_features=embed_dim, bias=False)
        self.W_k = nn.Linear(
            in_features=embed_dim, out_features=embed_dim, bias=False
        )
        self.W_v = nn.Linear(
            in_features=embed_dim, out_features=embed_dim, bias=False
        )
        self.row_index = row_index
        self.col_index = col_index